# Generated by Django 6.0.1 on 2026-04-22 16:30

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_orderitem_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=datetime.datetime(2026, 4, 22, 16, 29, 55, 557074, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
